{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "harbor-operator.fullname" . }}
  labels:
{{ include "harbor-operator.labels" . | indent 4 }}
{{- if .Values.metrics.serviceMonitor.labels }}
{{ toYaml .Values.metrics.serviceMonitor.labels | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "harbor-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: https
      scheme: {{ ternary "https" "http" .Values.metrics.secure }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
