---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-password
  namespace: harbor-operator-system
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: Harbor12345
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: HarborConnection
metadata:
  name: harbor-main
  namespace: harbor-operator-system
spec:
  baseURL: http://harbor-core.default.svc.cluster.local
  credentials:
    type: basic
    username: admin
    passwordSecretRef:
      name: harbor-admin-password
      key: HARBOR_ADMIN_PASSWORD
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: ghcr
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: github-ghcr
  name: ghcr
  description: GitHub Container Registry
  url: https://ghcr.io
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: registry-gitlab-com
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: registry.gitlab.com
  description: Gitlab Container Registry
  url: https://registry.gitlab.com
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: docker-hub
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-hub
  name: docker-hub
  description: Docker Container Registry
  url: https://hub.docker.com
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: gcr
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: gcr
  description: ""
  url: https://mirror.gcr.io
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: k8s
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: k8s
  description: ""
  url: https://registry.k8s.io
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: 8gears-container-registry-com
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: 8gears.container-registry.com
  description: ""
  url: https://8gears.container-registry.com
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: oci-external-secrets-io
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: oci.external-secrets.io
  description: ""
  url: https://oci.external-secrets.io
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: us-docker-pkg-dev
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: us-docker.pkg.dev
  description: ""
  url: https://us-docker.pkg.dev
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: public-ecr-aws
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: public.ecr.aws
  description: Uses public.ecr.aws
  url: https://public.ecr.aws/
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: quay
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: quay
  description: ""
  url: https://quay.io
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  name: docker
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  type: docker-registry
  name: docker
  description: ""
  url: https://registry-1.docker.io
  insecure: false
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: ghcr-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: ghcr
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: quay-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: quay
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: gcr-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: gcr
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: k8s-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: k8s
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: docker-hub-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: docker-hub
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: 8gears-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: 8gears.container-registry.com
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: external-secrets-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: oci.external-secrets.io
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: gitlab-registry-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: registry.gitlab.com
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: us-pkg-cache
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: us-docker.pkg.dev
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: helm-charts
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  name: public-ecr-aws
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  name: ""
  public: true
  metadata:
    public: "true"
  registryName: public.ecr.aws
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-user-public-user
  namespace: harbor-operator-system
type: Opaque
stringData:
  password: "PublicUser-ChangeMe-123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-user-kube-kraken-user
  namespace: harbor-operator-system
type: Opaque
stringData:
  password: "KubeKraken-ChangeMe-123!"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: User
metadata:
  name: public-user
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  username: public-user
  email: public-user@example.com
  realname: Public User
  comment: Public test user
  passwordSecretRef:
    name: harbor-user-public-user
    key: password
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: User
metadata:
  name: kube-kraken-user
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  username: kube-kraken-user
  email: kube-kraken-user@example.com
  realname: Kube Kraken User
  comment: Kube kraken test user
  passwordSecretRef:
    name: harbor-user-kube-kraken-user
    key: password
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: 8gears-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: 8gears-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: docker-hub-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: docker-hub-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: external-secrets-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: external-secrets-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: gcr-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: gcr-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: ghcr-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: ghcr-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: gitlab-registry-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: gitlab-registry-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: k8s-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: k8s-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: public-ecr-aws-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: public-ecr-aws
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: quay-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: quay-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: RetentionPolicy
metadata:
  name: us-pkg-cache-retention
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  projectRef:
    name: us-pkg-cache
  algorithm: or
  trigger:
    kind: Schedule
    settings:
      cron: 0 0 0 * * *
  rules:
    - action: retain
      template: latestPushedK
      params:
        latestPushedK:
          value: 3
      tagSelectors:
        - kind: doublestar
          decoration: matches
          pattern: "**"
      scopeSelectors:
        repository:
          - kind: doublestar
            decoration: repoMatches
            pattern: "**"
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: GCSchedule
metadata:
  name: harbor-gc-schedule
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  schedule:
    type: Weekly
    cron: 0 0 0 * * 0
  parameters:
    deleteUntagged: true
    workers: 2
---
apiVersion: harbor.harbor-operator.io/v1alpha1
kind: PurgeAuditSchedule
metadata:
  name: harbor-purge-audit
  namespace: harbor-operator-system
spec:
  harborConnectionRef: harbor-main
  schedule:
    type: Daily
    cron: 0 0 0 * * *
  parameters:
    auditRetentionHour: 720
    includeEventTypes: delete_artifact,create_artifact,pull_artifact,other
    dryRun: false
