image:
  repository: ghcr.io/rkthtrifork/harbor-operator/harbor-operator
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

metrics:
  enabled: false
  secure: true
  bindAddress: ":8443"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podLabels: {}
priorityClassName: ""

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - "ALL"

env: []

pdb:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

nodeSelector: {}
tolerations: []
affinity: {}

topologySpreadConstraints: []
