---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - clusterharborconnections
  - configurations
  - gcschedules
  - harborconnections
  - immutabletagrules
  - labels
  - members
  - projects
  - purgeauditschedules
  - quotas
  - registries
  - replicationpolicies
  - retentionpolicies
  - robots
  - scanallschedules
  - scannerregistrations
  - usergroups
  - users
  - webhookpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - clusterharborconnections/finalizers
  - configurations/finalizers
  - gcschedules/finalizers
  - harborconnections/finalizers
  - immutabletagrules/finalizers
  - labels/finalizers
  - members/finalizers
  - projects/finalizers
  - purgeauditschedules/finalizers
  - quotas/finalizers
  - registries/finalizers
  - replicationpolicies/finalizers
  - retentionpolicies/finalizers
  - robots/finalizers
  - scanallschedules/finalizers
  - scannerregistrations/finalizers
  - usergroups/finalizers
  - users/finalizers
  - webhookpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - clusterharborconnections/status
  - configurations/status
  - gcschedules/status
  - harborconnections/status
  - immutabletagrules/status
  - labels/status
  - members/status
  - projects/status
  - purgeauditschedules/status
  - quotas/status
  - registries/status
  - replicationpolicies/status
  - retentionpolicies/status
  - robots/status
  - scanallschedules/status
  - scannerregistrations/status
  - usergroups/status
  - users/status
  - webhookpolicies/status
  verbs:
  - get
  - patch
  - update
