---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - registries/finalizers
  verbs:
  - update
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - registries/status
  verbs:
  - get
  - patch
  - update
