---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - harborconnections
  - members
  - projects
  - registries
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - harborconnections/finalizers
  - members/finalizers
  - projects/finalizers
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - harbor.harbor-operator.io
  resources:
  - harborconnections/status
  - members/status
  - projects/status
  - registries/status
  - users/status
  verbs:
  - get
  - patch
  - update
