apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  labels:
    app.kubernetes.io/name: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: registry-sample
spec:
  harborConnectionRef: harborconnection-sample
  insecure: false
  # I recommend not specifying this field in which case the metadata.name will be used
  # name: registry-sample
  type: github-ghcr
  url: https://ghcr.io
  # Optional credentials
  # credential:
  #   type: basic
  #   accessKeySecretRef:
  #     name: ghcr-credentials
  #     key: access_key
  #   accessSecretSecretRef:
  #     name: ghcr-credentials
  #     key: access_secret
  # Optional custom CA certificate
  # caCertificateRef:
  #   name: ghcr-ca
  #   key: ca.crt
