apiVersion: harbor.harbor-operator.io/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  harborConnectionRef: harborconnection-sample
  email: example@email.com
  # I recommend not specifying this field in which case the metadata.name will be used
  # username: project-sample
  password: Password1
  realname: User Sample
