apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Registry
metadata:
  labels:
    app.kubernetes.io/name: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: registry-sample
spec:
  harborConnectionRef: harborconnection-sample
  insecure: false
  # I recommend not specifying this field in which case the metadata.name will be used
  # name: registry-sample
  type: github-ghcr
  url: https://ghcr.io
