apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  harborConnectionRef: harborconnection-sample
  name: project-sample
  public: false
