apiVersion: harbor.harbor-operator.io/v1alpha1
kind: Quota
metadata:
  labels:
    app.kubernetes.io/name: harbor-operator
    app.kubernetes.io/managed-by: kustomize
  name: quota-sample
spec:
  harborConnectionRef:
    name: harborconnection-sample
    kind: HarborConnection
  projectRef:
    name: project-sample
  hard:
    storage: 1073741824
