# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/harbor.harbor-operator.io_registries.yaml
- bases/harbor.harbor-operator.io_projects.yaml
- bases/harbor.harbor-operator.io_users.yaml
- bases/harbor.harbor-operator.io_members.yaml
- bases/harbor.harbor-operator.io_harborconnections.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
