name: PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Validate pull request title
        uses: ytanikin/pr-conventional-commits@1.4.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert","build"]'
          add_label: "true"
          custom_labels: '{"feat":"feat","fix":"fix","docs":"docs","test":"test","ci":"ci","refactor":"refactor","perf":"perf","chore":"chore","revert":"revert","build":"build"}'
