name: Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6.0.2

      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          make test
